import React from 'react';

export type NavItemName = 'Início' | 'Conversar com Lucresia' | 'Essência da Marca' | 'Projetos' | 'Gerador de Pautas' | 'Avaliador de Conteúdo' | 'Analisador de Resultados' | 'Analisador Sensorial' | 'Laboratório Elevare' | 'Trilhas' | 'Estúdio Visual' | 'Calendário Editorial' | 'Automação de Publicação' | 'Jornada da Cliente' | 'HUB';

export type ActiveView = NavItemName;

export interface ChatMessage {
  id: string;
  sender: 'user' | 'lucresia';
  content: React.ReactNode;
}

export interface NavItem {
  name: NavItemName;
  icon?: React.FC<{ className?: string }>;
  tag?: 'Beta' | 'Novo!' | 'Em Breve';
  isSectionTitle?: boolean;
}

export type TrilhaCategory = 'Relacionamento & Fidelização' | 'Criação de Conteúdo' | 'Vendas & Ofertas' | 'Estratégia & Negócios';

export interface Trilha {
    id: string;
    icon: React.FC<{ className?: string }>;
    title: string;
    description: string;
    category: TrilhaCategory;
    steps?: number;
    whyItMatters?: string;
    howItWorks?: string[];
    essentialElements?: string[];
    lucresiaTip?: string;
    relatedTools?: string[];
    action?: 'CREATE_FUNNEL';
    templatePosts?: Array<Partial<Omit<ScheduledPost, 'id'>> & { dayOffset: number; title: string }>;
}

export interface TourStep {
    title: string;
    content: React.ReactNode;
    target?: string; // CSS selector for the element to highlight
}

export interface EssenciaField {
    id: string;
    title: string;
    icon: React.FC<{ className?: string }>;
    content: string;
    autoGenerated?: boolean;
}

export interface Essencia {
    id: string;
    title: string;
    description: string;
    icon: React.FC<{ className?: string }>;
    fields: EssenciaField[];
}

export type AspectRatio = '1:1' | '3:4' | '4:3';

// Fix: Add missing AjustadoraOutput and ContentVariation types.
export interface ContentVariation {
    variant: string;
    text: string;
    cta: string;
    how: string[];
}

export interface AjustadoraOutput {
    instagram: ContentVariation[];
    reel: ContentVariation[];
    whatsapp: ContentVariation[];
    [key: string]: ContentVariation[];
}

// Types for Calendar View
export type PostStatus = 'Ideia' | 'Rascunho' | 'Agendado' | 'Publicado';

export interface PostPerformanceMetrics {
    reach?: number;
    saves?: number;
}
export interface PostPerformance {
    rating: 'fraco' | 'normal' | 'incrivel';
    metrics?: PostPerformanceMetrics;
}

export interface ScheduledPost {
    id: string;
    title: string;
    date: string; // YYYY-MM-DD
    status: PostStatus;
    content: string;
    performance?: PostPerformance;
    projectId?: string;
}

export interface ContentSuggestion {
    id: string;
    title: string;
    category: 'Autoridade' | 'Vendas' | 'Prova Social' | 'Lifestyle';
    prompt: string;
}

// Types for Projects
export type ProjectType = 'Campanha de Lançamento' | 'Funil de Vendas' | 'Planejamento de Conteúdo' | 'Linha Editorial' | 'Anúncios' | 'E-mail Marketing' | 'Branding & Posicionamento';
export type ProjectStatus = 'Planejamento' | 'Ativo' | 'Concluído' | 'Pausado';

export interface Project {
    id: string;
    name: string;
    description: string;
    type: ProjectType;
    tags: string[];
    modified: string;
    status: ProjectStatus;
    goal?: string;
}

export interface ProjectTemplate {
    id: string;
    name: string;
    description: string;
    type: ProjectType;
    tags: string[];
    templatePosts?: Array<Partial<Omit<ScheduledPost, 'id' | 'projectId'>> & { dayOffset: number; title: string }>;
}


export interface Workspace {
    id: string;
    name: string;
    essencias: Essencia[];
    projects: Project[];
    scheduledPosts: ScheduledPost[];
    defaultEssenciaId?: string;
}

export interface Toast {
    id: string;
    message: string;
    type: 'success' | 'error' | 'info';
}

export interface PautaEmail {
    assunto: string;
    corpo: string;
}

export interface PautaOutput {
    carrossel: string[];
    legenda: string;
    reels: string;
    googleMeuNegocio: string;
    whatsapp: string;
    email: PautaEmail;
    mentoriaRapida: string;
}

export interface ContentEvaluation {
    clareza: string;
    conexao: string;
    conversao: string;
}

export interface ContentEvaluationScores {
    clareza: number;
    conexao: number;
    conversao: number;
}

export interface ContentEvaluationOutput {
    notas: ContentEvaluationScores;
    feedback: ContentEvaluation;
    versaoOtimizada: string;
    mentoriaRapida: string;
}

export interface ResultsAnalysisOutput {
    insights: string[];
    recommendations: string[];
}

export interface JourneyStage {
    id: string;
    title: string;
    description: string;
    icon: React.FC<{ className?: string }>;
    mentorTip: string;
    generationPrompt: string;
}

export interface RealtimeSuggestion {
    suggestion: string;
    reason: string;
}

export interface CompetitorAnalysis {
    profile: string;
    toneOfVoice: string;
    visualStrategy: string;
    contentPillar: string;
}

export interface CompetitorAnalysisOutput {
    analysis: CompetitorAnalysis[];
    opportunity: string;
}

export interface LabTool {
    name: string;
    description: string;
    url: string;
}

export interface Badge {
    id: string;
    icon: string;
    title: string;
    description: string;
}

export interface UserProfile {
    name: string;
    elo: number;
    badges: Badge[];
}